name: Update Documentation

on:
  workflow_call:
  workflow_dispatch:

permissions: { }

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Documentation
        uses: devcontainers/action@v1
        with:
          generate-docs: "true"
          base-path-to-features: "./src"

      - name: Create PR for documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git config pull.rebase false

          branch="docs/${{ github.run_id }}"
          git switch -c "$branch"
          git add ./*/**/README.md
          git commit -m "docs: automated update"

          git push origin "$branch"
          message="Automated documentation update"
          gh pr create --title "$message" --body "$message" --base main --head "$branch"
