name: Release Features

on:
  workflow_dispatch:

permissions: { }

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish Features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      contents: write
      pull-requests: write

    uses: ./.github/workflows/docs.yaml
